= Trucs et astuces pour Debian

== Paquets utiles

Voici quelques paquets utiles à mettre sur une installation vierge : 

----
apt-get install -y vim fail2ban net-tools dos2unix
----

Si vous êtes sur VMware : 

----
apt-get install -y open-vm-tools
----

== Ajout d'un bashrc coloré

----
rm -rf /root/.bashrc
wget https://raw.githubusercontent.com/jeedom/core/stable/install/bashrc -O /root/.bashrc
dos2unix /root/.bashrc
----

== Autoriser la connexion root en SSH

Il faut éditer le fichier /etc/ssh/sshd_config et changer : 

----
PermitRootLogin without-password
----

Par :

----
PermitRootLogin yes
----

== Monter un partage Samba

Installation du paquet cifs

----
apt-get install -y cifs-utils
----

Créer le point de montage : 

----
mkdir /mnt/mon_partage
----

[NOTE]
Il faut adapter mon_partage en fonction de votre besoin

Ajout du montage dans /etc/fstab
----
//IP_SERVER_SAMBA/mon_partage /mnt/mon_partage cifs uid=0,rw,user=TODO,password=TODO 0 0
----

[NOTE]
Vous devez changer les TODO pour user et password par rapport à votre configuration

== Passage de Jessie à Stretch

Il faut éditer le fichier /etc/apt/sources.list et remplacer tous les jessie par stretch, puis faire : 

---- 
apt-get update
apt-get dist-upgrade
----

[IMPORTANT]
Si vous passez de jessie à Stretch sans refaire l'installation de Jeedom il faut desactiver le private tmp d'apache sinon Jeedom ne marchera pas : 

----
rm /etc/systemd/system/multi-user.target.wants/apache2.service
cp /lib/systemd/system/apache2.service /etc/systemd/system/multi-user.target.wants/
sed -i 's/PrivateTmp=true/PrivateTmp=false/g' /etc/systemd/system/multi-user.target.wants/apache2.service
----

