= Remise à zéro de votre mot de passe Jeedom

Nous allons voir ici comment changer votre mot de passe Jeedom si vous l'avez oublié directement en modifiant celui-ci en base de données.

La première chose est de se connecter en SSH à Jeedom (avec un logiciel type kitty ou putty). Vous trouverez les identifiants SSH link:https://jeedom.fr/doc/documentation/installation/fr_FR/doc-installation.html[ici].

Une fois connecté il vous faut récuperer les identifiants de la base de données : 

[source,bash]
cat /var/www/html/core/config/common.config.php

Ici vous trouverez le mot de passe pour accéder à la base de données jeedom, il faut ensuite faire : 

[source,bash]
mysql -ujeedom -p 

Là il vous demande le mot de passe récupéré plus haut. Tapez ensuite : 

[source,bash]
use jeedom;
REPLACE INTO user SET `login`='admin',password=SHA1('admin'),rights='{"admin":"1"}', enable='1';

Voilà vous pouvez vous connecter à nouveau à votre jeedom avec les identifiants admin/admin ce qui vous permettra de modifier le mot de passe des autres comptes.
