Vous trouverez ici la documentation pour installer Jeedom sur la plupart des systèmes linux (testée et approuvée sur la distribution Debian)

[IMPORTANTE]
Debian 8 est la distribution officiellement supportée, l'utilisation d'une autre distribution est à proscrire au risque d'obtenir comme réponse du support de devoir restaurer votre Jeedom sur une image officielle.
Si vous ne maitriser pas un minimum les environnements Linux, nous vous conseillons de partir sur une image officielle (OVF) ou l'utilisation d'une Mini+ ou Smart (disponible prochainement).

Connectez-vous en SSH à votre système et faites : 

----
wget https://raw.githubusercontent.com/jeedom/core/stable/install/install.sh
chmod +x install.sh
./install.sh
----

Il vous suffit ensuite d'aller sur IP_MACHINE_JEEDOM

[NOTE]
Les identifiants par défaut sont admin/admin

[NOTE]
Les arguments suivants sont utilisables :
-w = dossier webserver
-z = installation dependances z-wave
-m = mot de passe root mysql désiré

-----

./install.sh -w /var/www/html -z -m Jeedom

-----



Ensuite vous pouvez suivre la documentation https://www.jeedom.fr/doc/documentation/premiers-pas/fr_FR/doc-premiers-pas.html[Premier pas avec Jeedom]