= Liste de compatibilité Jeedom

== Matériels
include::hardware.asciidoc[]

'''
== Images
include::images.asciidoc[]

'''
== Logiciel
include::software.asciidoc[]

== Clef USB/Module d'extension
Contrôleur ENOCEAN : 

- Clef USB EnOcean USB300
- Clef USB EnOcean USB310 (Recommandé)

Interface RFXCOM :

- RFXtrx433 USB
- RFXtrx433E USB (Recommandé)

Passerelle EDISIO :

- Dongle Edisio (Recommandé)

Indicateur Led :

- blink(1) mk2 (Recommandé)

Dongle GSM :

- HUAWEI E220 (Recommandé)
- Alcatel one touch X220L
- HSDPA 7.2MBPS 3G Wireless

Contrôleur Z-WAVE :

- SIGMA DESIGNS Contrôleur Z-Wave Plus USB
- Z-WAVE.ME - Mini contrôleur USB Z-Wave Plus UZB1
- AEON LABS Contrôleur Z-Wave Aeon Labs Z-Stick S2
- AEON LABS - Contrôleur USB Z-Wave Plus Z-Stick GEN5 (Recommandé)

'''
== Modules Zwave
Vous trouverez la liste https://jeedom.github.io/documentation/zwave/fr_FR/equipement.compatible.html[ici]

'''
== Modules EnOcean
Vous trouverez la liste https://jeedom.github.io/documentation/enocean/fr_FR/equipement.compatible.html[ici]

'''
== Modules Edisio
Vous trouverez la liste https://jeedom.github.io/documentation/edisio/fr_FR/-equipement.compatible.html[ici]

'''
== Modules RFXcom
Vous trouverez la liste https://jeedom.github.io/documentation/rfxcom/fr_FR/equipement.compatible.html[ici]

'''
== Caméras
Vous trouverez la liste https://jeedom.github.io/documentation/camera/fr_FR/equipement.compatible.html[ici]

== Plateforme matérielle recommandée

L'équipe jeedom vous recommande (en fonction de votre budget) :

- Jeedom Smart (tout est préinstallé, vous n'avez rien à faire)
- Odroid C2 (meilleur rapport performance/prix)
- Intel Nuc gen6 (des performances extrêmes, voir la catégorie tuto pour le choix dans les differents modèles et l'installation)

== Hardware Loïc

include::hardwareloic.asciidoc[]