= Tipps und Tricks für Debian

== Nützliche Pakete

Hier sind einige nützliche Pakete, die auf eine unberührte Installation nachinstalliert werden können :  

----
apt-get install -y vim fail2ban net-tools dos2unix
----

Wenn Sie auf VMware sind : 

----
apt-get install -y open-vm-tools
----

== Eine farbige bashrc hinzufügen

----
rm -rf /root/.bashrc
wget https://raw.githubusercontent.com/jeedom/core/stable/install/bashrc -O /root/.bashrc
dos2unix /root/.bashrc
----

== Eine root Verbindung in SSH erlauben 

Il faut éditer le fichier /etc/ssh/sshd_config et changer : 

----
PermitRootLogin without-password
----

Ändern in :

----
PermitRootLogin yes
----

== Monter un partage Samba

cifs Paket installieren

----
apt-get install -y cifs-utils
----

Den Mount-Punkt erstellen : 

----
mkdir /mnt/mon_partage
----

[NOTE]
Man muß mon_partage nach Ihren Bedürfnissen entsprechend anpassen

Zusatz der Montage in /etc/fstab
----
//IP_SERVER_SAMBA/mon_partage /mnt/mon_partage cifs uid=0,rw,user=TODO,password=TODO 0 0
----

[NOTE]
Vous devez changer les TODO pour user et password par rapport à votre configuration

== Umstellung von Jessie in Stretch

Il faut éditer le fichier /etc/apt/sources.list et remplacer tous les jessie par stretch, puis faire : 

---- 
apt-get update
apt-get dist-upgrade
----

[IMPORTANT]
Si vous passez de jessie à Stretch sans refaire l'installation de Jeedom il faut desactiver le private tmp d'apache sinon Jeedom ne marchera pas : 

----
rm /etc/systemd/system/multi-user.target.wants/apache2.service
cp /lib/systemd/system/apache2.service /etc/systemd/system/multi-user.target.wants/
sed -i 's/PrivateTmp=true/PrivateTmp=false/g' /etc/systemd/system/multi-user.target.wants/apache2.service
----

